config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    # "" 은 / 를 의미한다.
    path("", room_views.HomeView.as_view(), name="home")
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete-verification"
    ),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
]

templates/partials/footer.html
{% load static %}
<div class="col-center relative pt-4 pb-6 ">
    <div class="h-px w-85vw max-w-7xl border-b-2 border-gray-100 mb-8 relative -top-9"></div>
</div>
<footer class="flex justify-center relative w-full -mt-12 font-medium text-xs text-gray-400">
    <span class="my_clock"></span>&nbsp;<span>&copy; NBNB</span>
</footer>

<script src="{% static 'javascripts/index.js' %}"></script>

templates/partials/messages.html
{% if messages %}
<ul class="absolute -top-16 mx-auto z-10 flex justify-center">
    {% for message in messages %}
    <li class="message message-shape {% if message.tags %}{{ message.tags }}{% endif %}">
        {{message}}
    </li>
    {% endfor %}
</ul>
{% endif %}

templates/partials/nav.html
<ul class="ul-nav pr-4 w-full">
        
    {% if user.is_authenticated %}
        <li class="li-nav"><a href="{{user.get_absolute_url}}">Profile</a></li>
        <li class="li-nav w-14"><a href="{% url 'users:logout' %}">Log out</a></li>
    {% else %}
        <li class="li-nav"><a href="/admin/">Admin</a></li>
        <li class="li-nav w-14"><a href="{% url 'users:login' %}">Log in</a></li>
        <li class="li-nav w-14"><a href="{% url 'users:signup' %}">Sign up</a></li>
    {% endif %}
</ul>

templates/partials/social_login.html
<a href="{% url 'users:github-login' %}" class="w-full">
    <div class="relative border-0 col-center rounded-sm w-full h-12 px-2 text-sm my-1 bg-gray-700">
        <svg height="32" aria-hidden="true" viewBox="0 0 16 16" version="1.1" width="32" data-view-component="true" style="fill:white" class="absolute left-4">
            <path fill-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"></path>
        </svg>
        <span class="text-white font-medium">
            Continue with Github
        </span> 
    </div>
</a>
<a href="{% url 'users:kakao-login' %}" class="w-full">
    <div class="border-0 col-center rounded-sm w-full h-12 px-2 text-sm my-1 bg-yellow-400">
        <img src="/static/img/Kakao_Mark.png" class="absolute left-8 w-10" />
        <span class="text-white font-medium">
            Continue with Kakao
        </span>
    </div>
</a>
<div class="flex w-full items-center">
    <div class="h-px bg-gray-300 w-full"></div>
        <span class="px-2 pb-1"> or </span>
    <div class="h-px bg-gray-300 w-full"></div>
</div>