config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    # "" 은 / 를 의미한다.
    path("", room_views.HomeView.as_view(), name="home")
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", views.room_detail, name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
]

templates/mixins/room_card.html
<div class="flex flex-col items-center min-w-1/4 mb-6 px-2">
    <a href="{% url 'rooms:detail' room.pk %}">
    <!-- Room Photo -->
        <div class="h-50 w-1280 w-1000 w-0810 w-0510 relative flex flex-col justify-between items-center rounded-md bg-cover bg-center" style="background-image: url({{room.first_photo}});">
            <div class="flex px-2 w-11/12 h-6 absolute top-4 items-center rounded-md">
                <span class="text-sm text-gray-600 font-semibold"></span>
            </div>
            <div class="flex items-center px-2 w-11/12 h-8 rounded-md absolute bg-opacity-90 bottom-2 bg-gray-50">
                <span class="text-sm text-gray-600 truncate ...">{{room.name}}</span>
            </div>
        </div>
        <!-- Infomation -->
        <div class="flex flex-wrap justify-between px-2 w-1280 w-1000 w-0810 w-0510 pt-2 text-sm">
            <div class="flex justify-between w-full">
                    <span class="w-5/6 leading-4 truncate ...">{{room.city}} / {{room.country.name}}</span>
                <div class="flex w-1/6 justify-end relative text-xs text-gray-300">
                    {{room.total_rating}}
                </div>
            </div>
            <div class="flex justify-between w-full">
                <!-- SuperHost -->
                <div class="pt-px relative">
                    {% if room.host.superhost %}
                    {% include 'mixins/auth/superhost.html' %}
                    {% endif %}
                </div>
                <!-- Star-rate -->
                <div class="w-10">
                    <!-- star-rate-empty -->
                    <div class="star-rate z-0 relative -left-9" style="background-image: url(/static/img/star_blank_small.png);"></div>
                    <!-- star-rate-full -->
                    <div class="star-rate z-10 relative -top-4 -left-9" style="background-image: url(/static/img/star_small.png); clip-path: polygon(0 0, {{room.total_rate}}% 0, {{room.total_rate}}% 100%, 0% 100%);"></div>
                </div>
            </div>
        </div>
    </a>
</div>

templates/mixins/user_avatar.html
{% if user.avatar %}
<div class="h-24 w-24 rounded-full bg-center bg-cover" style="background-image: url('{{user_obj.avatar.url}}');"></div>
{% else %}
<div class="col-center h-24 w-24 bg-gray-400 font-semibold text-4xl text-white rounded-full">
    <span>{{user.first_name|first|capfirst}}</span>
</div>
{% endif %}