config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    # "" 은 / 를 의미한다.
    path("", room_views.HomeView.as_view(), name="home")
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", views.room_detail, name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
]

templates/base.html
{% load static %}
{% load uuid %}
<!DOCTYPE html>
<html lang="en" class="font-display scroll-smooth">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}?{% uuid_code %}" />
    <title>{% block page_title %}{% endblock page_title %}| Nbnb</title>
  </head>
  <body>
    <header class="col-center w-full">
      {% include "partials/messages.html" %}
      <div class="flex w-max max-w-7xl h-full">
        <div class="flex w-screen pl-4 min-w-1/2 items-center h-full justify-self-auto">
          <a href="{% url 'core:home' %}">
            <img class="w-10 min-w-10" src="{% static 'img/logo.png' %}" />
          </a>
          {% block search-bar %}
          <form method="get" action="{% url 'rooms:search' %}" class="flex m-0 pl-2 w-full h-full max-w-4xl items-center">
            <input type="hidden" name="country" value="KR" />
            <input name="city" placeholder="Search by City" class="search w-11/12"/>
          </form>
          {% endblock search-bar %}
          {% include 'partials/nav.html' %}
        </div>
      </div>
    </header>
      <! -- room_list -- !>
      {% block content %}{% endblock content %}
      {% include 'partials/footer.html' %}
  </body>
</html>